module.exports.songs = [
	{
		title: "As I Am",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001483/MysticBeats/English/Justin_Bieber_-_As_I_Am_Visualizer_ft._Khalid_tle9yh.mp3",
		language: "English",
	},
	{
		title: "Hold On",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001500/MysticBeats/English/Justin_Bieber_-_Hold_On_Lyric_Video_ymr4il.mp3",
		language: "English",
	},
	{
		title: "Peaches",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001497/MysticBeats/English/Justin_Bieber_-_Peaches_ft._Daniel_Caesar_Giveon_Lyric_Video_wbhf7m.mp3",
		language: "English",
	},
	{
		title: "Somebody",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001486/MysticBeats/English/Justin_Bieber_-_Somebody_Visualizer_tkb4yj.mp3",
		language: "English",
	},
	{
		title: "Cold Water",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001478/MysticBeats/English/Major_Lazer_-_Cold_Water_feat._Justin_Bieber_amp_M%C3%98_Official_Lyric_Video_aciyxz.mp3",
		language: "English",
	},
	{
		title: "I Don't Care",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001488/MysticBeats/English/Ed_Sheeran_Justin_Bieber_I_Dont_Care_Official_Audio_ndisfi.mp3",
		language: "English",
	},
	{
		title: "Mood (Remix)",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001495/MysticBeats/English/24kGoldn_Justin_Bieber_J_Balvin_iann_dior_-_Mood_Remix_-_Official_Lyric_Video_sfdzvt.mp3",
		language: "English",
	},
	{
		title: "Confirmation",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001495/MysticBeats/English/Justin_Bieber_-_Confirmation_Audio_q6egj2.mp3",
		language: "English",
	},
	{
		title: "Stuck With U",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001499/MysticBeats/English/Ariana_Grande_Justin_Bieber_-_Stuck_with_U_Lyric_Video_j65rg5.mp3",
		language: "English",
	},
	{
		title: "Sorry",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001486/MysticBeats/English/Justin_Bieber_-_Sorry_Official_Lyric_Video_pzgu28.mp3",
		language: "English",
	},
	{
		title: "Let Me Love You",
		artist: "Justin Bieber",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625001499/MysticBeats/English/DJ_Snake_ft._Justin_Bieber_-_Let_Me_Love_You_Lyric_Video_cf5fnw.mp3",
		language: "English",
	},
	{
		title: "Burn It Down",
		artist: "Linkin Park",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002631/MysticBeats/English/BURN_IT_DOWN_Official_Lyric_Video_-_Linkin_Park_djfun2.mp3",
		language: "English",
	},
	{
		title: "Castle Of Glass",
		artist: "Linkin Park",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002636/MysticBeats/English/MP3DOWNLOAD.TO_CASTLE_OF_GLASS-256k_haidnj.mp3",
		language: "English",
	},
	{
		title: "Numb",
		artist: "Linkin Park",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002636/MysticBeats/English/MP3DOWNLOAD.TO_Linkin_Park_-_Numb_Lyrics_-256k_ogwupw.mp3",
		language: "English",
	},
	{
		title: "Waiting For The End",
		artist: "Linkin Park",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002637/MysticBeats/English/Waiting_For_The_End_Official_Lyric_Video_-_Linkin_Park_oeglwz.mp3",
		language: "English",
	},
	{
		title: "Sing Me To Sleep",
		artist: "Alan Walker",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002621/MysticBeats/English/Alan_Walker_-_Sing_Me_To_Sleep_Lyrics_mm3ush.mp3",
		language: "English",
	},
	{
		title: "Darkside",
		artist: "Alan Walker",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002631/MysticBeats/English/Alan_Walker_-_Darkside_Lyrics_ft._AuRa_and_Tomine_Harket_cixrxo.mp3",
		language: "English",
	},
	{
		title: "Faded",
		artist: "Alan Walker",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002626/MysticBeats/English/Alan_Walker_-_Faded_Audio_r8voyr.mp3",
		language: "English",
	},
	{
		title: "Alone",
		artist: "Alan Walker",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002633/MysticBeats/English/Alan_Walker_-_Alone_Lyrics_tn1j2l.mp3",
		language: "English",
	},
	{
		title: "The Spectre",
		artist: "Alan Walker",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002626/MysticBeats/English/Alan_Walker_-_The_Spectre_Official_Audio_HQ_xg0fat.mp3",
		language: "English",
	},
	{
		title: "Let It Go",
		artist: "DJ Khaled",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002626/MysticBeats/English/DJ_Khaled_-_LET_IT_GO_Official_Audio_ft._Justin_Bieber_21_Savage_kkvkbn.mp3",
		language: "English",
	},
	{
		title: "No Brainer",
		artist: "DJ Khaled",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625002636/MysticBeats/English/DJ_Khaled_-_No_Brainer_Audio_ft._Justin_Bieber_Chance_the_Rapper_Quavo_u6mth0.mp3",
		language: "English",
	},
	{
		title: "Perfect To Me",
		artist: "Anne-Marie",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003145/MysticBeats/English/Anne-Marie_-_Perfect_To_Me_Official_Lyric_Video_d65fh2.mp3",
		language: "English",
	},
	{
		title: "2002",
		artist: "Anne-Marie",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003147/MysticBeats/English/Anne-Marie_-_2002_Official_Lyric_Video_wlmkj0.mp3",
		language: "English",
	},
	{
		title: "Friends (with Marshmello)",
		artist: "Anne-Marie",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003155/MysticBeats/English/FRIENDS_iklp8k.mp3",
		language: "English",
	},
	{
		title: "Our Song",
		artist: "Anne-Marie",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003143/MysticBeats/English/Anne-Marie_Niall_Horan_-_Our_Song_Lyrics_g33a6m.mp3",
		language: "English",
	},
	{
		title: "All We Know",
		artist: "The Chainsmokers",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003153/MysticBeats/English/The_Chainsmokers_-_All_We_Know_Audio_ft._Phoebe_Ryan_z53nzs.mp3",
		language: "English",
	},
	{
		title: "Closer",
		artist: "The Chainsmokers",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003151/MysticBeats/English/The_Chainsmokers_-_Closer_Lyrics_ft._Halsey_iw7aua.mp3",
		language: "English",
	},
	{
		title: "Takeaway",
		artist: "The Chainsmokers",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003142/MysticBeats/English/The_Chainsmokers_Illenium_-_Takeaway_Lyrics_ft._Lennon_Stella_mu2jn0.mp3",
		language: "English",
	},
	{
		title: "Call You Mine",
		artist: "The Chainsmokers",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625003142/MysticBeats/English/The_Chainsmokers_Bebe_Rexha_-_Call_You_Mine_Lyrics_xkruet.mp3",
		language: "English",
	},
	{
		title: "Sun Zara",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787782/MysticBeats/Hindi/07._Sun_Zarra_-_Sonu_Nigam_pwabfy.mp3",
		language: "Hindi",
	},
	{
		title: "Abhi Mujh Mein Kahin",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787781/MysticBeats/Hindi/Abhi_Mujh_Mein_Kahin-sonu_nigam_awoxmv.mp3",
		language: "Hindi",
	},
	{
		title: "Kal Ho Naa Ho",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Kal_Ho_Naa_Ho_-_sonu_nigam_roayri.mp3",
		language: "Hindi",
	},
	{
		title: "Main Agar Kahoon",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787777/MysticBeats/Hindi/Main_Agar_Kahoon_-_Om_Shanti_Om_128_Kbps_vxo82g.mp3",
		language: "Hindi",
	},
	{
		title: "Suraj Hua Maddham",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787774/MysticBeats/Hindi/Suraj_Hua_Maddham_-_sonu_nigam_bmxxw4.mp3",
		language: "Hindi",
	},
	{
		title: "Shukran Allah",
		artist: "Sonu Nigam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787773/MysticBeats/Hindi/Shukran_Allah.m4a_128_Kbps_okh5hs.mp3",
		language: "Hindi",
	},
	{
		title: "Agar Tum Mil Jao",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787781/MysticBeats/Hindi/Agar_Tum_Mil_JaoFemale_-_Zeher_128_Kbps_ur2b7i.mp3",
		language: "Hindi",
	},
	{
		title: "Manwa Laage",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787775/MysticBeats/Hindi/Manwa_Laage_128_Kbps_wvoggj.mp3",
		language: "Hindi",
	},
	{
		title: "Raabta",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787776/MysticBeats/Hindi/Raabta_Kehte_Hain_Khuda_Ne1_cf3ypn.mp3",
		language: "Hindi",
	},
	{
		title: "Sunn Raha Hai",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787773/MysticBeats/Hindi/Sunn_Raha_Hai_Female_xelx0w.mp3",
		language: "Hindi",
	},
	{
		title: "Ye Ishq Hai",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787771/MysticBeats/Hindi/Ye_Ishq_Hai_-_Jab_We_Met_128_Kbps_omaryz.mp3",
		language: "Hindi",
	},
	{
		title: "Saibo",
		artist: "Shreya Ghoshal",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787775/MysticBeats/Hindi/Saibo_-_Shor_in_the_City_128_Kbps_qepz9f.mp3",
		language: "Hindi",
	},
	{
		title: "Bolna",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Bolna_-_Arijit_Singh_np0n59.mp3",
		language: "Hindi",
	},
	{
		title: "Tera Chehra",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787776/MysticBeats/Hindi/Tera_Chehra_-_Sanam_Teri_Kasam_128_Kbps_hkjb9p.mp3",
		language: "Hindi",
	},
	{
		title: "Tera Yaar Hoon Main",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787771/MysticBeats/Hindi/Tera_Yaar_Hoon_Main_Sonu_Ke_Titu_Ki_Sweety_128_Kbps_hisxxl.mp3",
		language: "Hindi",
	},
	{
		title: "Tujhe Kitna Chahne Lage",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787771/MysticBeats/Hindi/Tujhe_Kitna_Chahne_Lage_-_arjit_singh_nfywz5.mp3",
		language: "Hindi",
	},
	{
		title: "Tum Hi Ho",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787771/MysticBeats/Hindi/Tum_Hi_Ho-arjit_singh_wlqymj.mp3",
		language: "Hindi",
	},
	{
		title: "Khairiyat",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787777/MysticBeats/Hindi/Khairiyat_Sad_-_Chhichhore_128_Kbps_a0ljow.mp3",
		language: "Hindi",
	},
	{
		title: "Phir Kabhi",
		artist: "Arijit Singh",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787775/MysticBeats/Hindi/Phir_Kabhi_M_S_Dhoni_-_The_Untold_Story_128_rgbuxi.mp3",
		language: "Hindi",
	},
	{
		title: "Dil Diyan Gallan",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Dil_Diyan_Gallan_Tiger_Zinda_Hai_128_Kbps_m1gojp.mp3",
		language: "Hindi",
	},
	{
		title: "Jeena Jeena",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Jeena_Jeena_uay3fx.mp3",
		language: "Hindi",
	},
	{
		title: "Khair Mangda",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787777/MysticBeats/Hindi/Khair_Mangda-_Mr-Jatt.com_cca0ka.mp3",
		language: "Hindi",
	},
	{
		title: "Kuch Is Tarah",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787777/MysticBeats/Hindi/Kuch_Is_Tarah-_Mr-Jatt.com_u1ntwa.mp3",
		language: "Hindi",
	},
	{
		title: "Tu Jaane Na",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787771/MysticBeats/Hindi/Tu_Jaane_Na_-_Ajab_Prem_Ki_Ghazab_Kahani_128_Kbps_uxn77s.mp3",
		language: "Hindi",
	},
	{
		title: "Tere Sang Yaara",
		artist: "Atif Aslam",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787772/MysticBeats/Hindi/Tere_Sang_Yaara_Rustom_128_Kbps_q1itpm.mp3",
		language: "Hindi",
	},
	{
		title: "Besabriyaan",
		artist: "Armaan Malik",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787781/MysticBeats/Hindi/Besabriyaan_M.s._Dhoni_The_Untold_Story_128_Kbps_b2edfi.mp3",
		language: "Hindi",
	},
	{
		title: "Sab Tera",
		artist: "Armaan Malik",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787774/MysticBeats/Hindi/Sab_Tera_Baaghi_128_Kbps_hlyz1u.mp3",
		language: "Hindi",
	},
	{
		title: "Buddhu Sa Mann",
		artist: "Armaan Malik",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Buddhu_Sa_Mann_Kapoor_And_Sons_128_Kbps_uod1kx.mp3",
		language: "Hindi",
	},
	{
		title: "Hua Hain Aaj Pehli Baar",
		artist: "Armaan Malik",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787779/MysticBeats/Hindi/Hua_Hain_Aaj_Pehli_Baar_Sanam_Re_128_Kbps_vuumsp.mp3",
		language: "Hindi",
	},
	{
		title: "Sau Aasmaan",
		artist: "Armaan Malik",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625787774/MysticBeats/Hindi/Sau_Aasmaan-_Mr-Jatt.com_t2px03.mp3",
		language: "Hindi",
	},
	{
		title: "Bandook",
		artist: "Karan Aujla",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801037/MysticBeats/Punjabi/Bandook_akthde.mp3",
		language: "Punjabi",
	},
	{
		title: "Don't Worry",
		artist: "Karan Aujla",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801036/MysticBeats/Punjabi/Dont_Worry_-_Karan_Aujla_DjPunjab.Com_x34hgq.mp3",
		language: "Punjabi",
	},
	{
		title: "Hint",
		artist: "Karan Aujla",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801034/MysticBeats/Punjabi/Hint_-_Karan_Aujla_DjPunjab.Com_zsozlt.mp3",
		language: "Punjabi",
	},
	{
		title: "Let 'em Play",
		artist: "Karan Aujla",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801032/MysticBeats/Punjabi/Let_em_Play_n6iqfo.mp3",
		language: "Punjabi",
	},
	{
		title: "Na Na Na",
		artist: "Karan Aujla",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801032/MysticBeats/Punjabi/Na_Na_Na_-_Karan_Aujla_DjPunjab.Com_lnacek.mp3",
		language: "Punjabi",
	},
	{
		title: "Brown Shortie",
		artist: "Sidhu Moose Wala",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801036/MysticBeats/Punjabi/Brown_Shortie_hy72lm.mp3",
		language: "Punjabi",
	},
	{
		title: "Burberry",
		artist: "Sidhu Moose Wala",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801036/MysticBeats/Punjabi/Burberry_Original_abnnui.mp3",
		language: "Punjabi",
	},
	{
		title: "Game",
		artist: "Sidhu Moose Wala",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801035/MysticBeats/Punjabi/Game_-_Sidhu_Moose_Wala_128_Kbps_bmmhpa.mp3",
		language: "Punjabi",
	},
	{
		title: "Malwa Block",
		artist: "Sidhu Moose Wala",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801033/MysticBeats/Punjabi/Malwa_Block_gvpwkj.mp3",
		language: "Punjabi",
	},
	{
		title: "Old Skool",
		artist: "Sidhu Moose Wala",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Old_Skool_Ft._Sidhu_Moose_Wala_-_Prem_Dhillon_DjPunjab.Com_yknjo1.mp3",
		language: "Punjabi",
	},
	{
		title: "Guns and Guts",
		artist: "Kaptaan",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801035/MysticBeats/Punjabi/Guns_And_Guts_-_amlijatt.in_i3ccro.mp3",
		language: "Punjabi",
	},
	{
		title: "Husann",
		artist: "Kaptaan",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801034/MysticBeats/Punjabi/Husann_-_amlijatt.in_abmzu6.mp3",
		language: "Punjabi",
	},
	{
		title: "Kikli",
		artist: "Kaptaan",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801033/MysticBeats/Punjabi/Kikli_pporhf.mp3",
		language: "Punjabi",
	},
	{
		title: "Tees Maar Khan",
		artist: "Kaptaan",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Tees_Maar_Khan_-_KpTaan_DjPunjab.Com_ncsyqw.mp3",
		language: "Punjabi",
	},
	{
		title: "Sharabi",
		artist: "Kaptaan",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Sharabi_-_amlijatt.in_j7zdq7.mp3",
		language: "Punjabi",
	},
	{
		title: "Toxic",
		artist: "AP Dhillon",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Toxic_gsk3na.mp3",
		language: "Punjabi",
	},
	{
		title: "Insane",
		artist: "AP Dhillon",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801033/MysticBeats/Punjabi/Insane_f66t2r.mp3",
		language: "Punjabi",
	},
	{
		title: "Goat",
		artist: "AP Dhillon",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801034/MysticBeats/Punjabi/Goat_iyohtr.mp3",
		language: "Punjabi",
	},
	{
		title: "Excuses",
		artist: "AP Dhillon",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801035/MysticBeats/Punjabi/Excuses_k8dnmm.mp3",
		language: "Punjabi",
	},
	{
		title: "Foreigns",
		artist: "AP Dhillon",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801035/MysticBeats/Punjabi/Foreigns_-_AP_Dhillon_DjPunjab.Com_ryowhh.mp3",
		language: "Punjabi",
	},
	{
		title: "Yaar Anmulle",
		artist: "Sharry Mann",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Yaar_Anmulle_x2hftd.mp3",
		language: "Punjabi",
	},
	{
		title: "Visa",
		artist: "Sharry Mann",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801031/MysticBeats/Punjabi/Visa_ymy5ge.mp3",
		language: "Punjabi",
	},
	{
		title: "Hostel",
		artist: "Sharry Mann",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801034/MysticBeats/Punjabi/Hostel_lurn0z.mp3",
		language: "Punjabi",
	},
	{
		title: "3 Peg",
		artist: "Sharry Mann",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801037/MysticBeats/Punjabi/3_Peg_ywuvis.mp3",
		language: "Punjabi",
	},
	{
		title: "Bhull Jai Na",
		artist: "Sharry Mann",
		file: "https://res.cloudinary.com/sujalsinha/video/upload/v1625801036/MysticBeats/Punjabi/Bhull_Jai_Na_oqnes9.mp3",
		language: "Punjabi",
	},
];
